import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { attachUploadFile } from '../lib/upload-file';
import { CircleNoteReader } from './circle-note-reader';
const gameLabels:Record<string,{name:string;hint:string}>={'matching':{name:'Match the pairs',hint:'Match each question with its answer.'},'quick-quiz':{name:'Quick quiz',hint:'Answer short questions at your own pace.'},'word-scramble':{name:'Word scramble',hint:'Unscramble an answer using the clue.'},'group-challenge':{name:'Circle challenge',hint:'Try the same questions and compare scores.'}};
const kinds = ['matching','quick-quiz','word-scramble','group-challenge'];
const blankPair = () => ({ front: '', back: '' });
const blankQuestion = () => ({ type:'identification', question:'', answer:'', options:[] as string[] });
const shuffle = <T,>(items:T[]) => { const a = [...items]; for(let i=a.length-1;i>0;i--) { const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; };
export function circleLibraryCopy(n:any) {
  const title=n.name;
  const question=(q:any)=>{const options=q.choices || q.options || [];const index=typeof q.answer==='number'?q.answer:typeof q.answer==='string' && /^\d+$/.test(q.answer)?Number(q.answer):null;return {type:options.length?'multiple-choice':'identification',question:q.question,answer:index===null?q.answer:options[index],options};};
  if(n.type==='notes')return {title,materialType:'notes',content:{notes:n.data?.notes}};
  if(n.type==='flashcards')return {title,materialType:'flashcards',content:{cards:(n.flashcards || n.data?.flashcards || []).map((c:any)=>({front:c.question || c.front,back:c.answer || c.back}))}};
  if(n.type==='test')return {title,materialType:'tests',content:{questions:(n.data?.questions || []).map(question)}};
  if(n.type==='game')return {title,materialType:'games',content:{kind:'quick-quiz',pairs:(n.data?.game || []).map((q:any)=>{const normalized=question(q);return {front:normalized.question,back:normalized.answer};})}};
  throw new Error('This material cannot be shared yet.');
}
export function CircleMaterials({ api,room,type,p,refresh,noteId,onBack }:any) {
  const singular=type==='notes'?'Note':type==='flashcards'?'Flashcard set':type==='tests'?'Test':'Game';
  const [librarySearch,setLibrarySearch]=useState(''),[libraryLimit,setLibraryLimit]=useState(8);
  const base = '/api/cappy/circles/'+room.id+'/materials';
  const [adding,setAdding] = useState(false), [source,setSource] = useState(''), [actions,setActions] = useState<string|null>(null);
  const [editor,setEditor] = useState<any>(null), [opened,setOpened] = useState<any>(null), [library,setLibrary] = useState<any[]>([]);
  const [error,setError] = useState(''), [busy,setBusy] = useState(false), [confirmation,setConfirmation] = useState<any>(null);
  const [card,setCard] = useState(0), [flipped,setFlipped] = useState(false), [answers,setAnswers] = useState<Record<number,string>>({}), [score,setScore] = useState<number|null>(null);
  const [match,setMatch] = useState<number|null>(null), [matched,setMatched] = useState<number[]>([]), [right,setRight] = useState<number[]>([]), [scrambled,setScrambled] = useState<string[]>([]), [notice,setNotice] = useState('');
  useEffect(()=>{ let live=true; api('/api/library').then((r:any)=>{ if(live) setLibrary([...(r.studyMaterials || []),...(r.flashcardSets || []).map((n:any)=>({...n,type:'flashcards'}))].filter((n:any)=>n.type===(type==='tests'?'test':type==='games'?'game':type))); }).catch((e:any)=>{ if(live) setError(e.message); }); return ()=>{ live=false; }; },[api,type]);
  useEffect(()=>{ if(opened && !room.materials.some((m:any)=>m.id===opened.id)) { setOpened(null); setNotice('This material was removed by a Circle member.'); } },[room.materials,opened]);
  const run = async(fn:()=>Promise<void>)=>{ if(busy)return; setBusy(true); setError(''); try { await fn(); } catch(e:any) { setError(e.message==='Choose your own Library Note.' && type!=='notes'?'Your '+type+' could not be shared because the Circle server needs the Library sharing update. You can still create one here.':e.message || 'Please try again.'); } finally { setBusy(false); } };
  const button = (label:string,fn:()=>void,disabled=false,primary=false)=><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={fn} disabled={busy || disabled} style={{ borderRadius:14,borderColor:p.line,borderWidth:1,padding:12,minHeight:44,marginTop:8,backgroundColor:primary?p.blue:p.softBlue,opacity:busy || disabled?.5:1 }}><Text style={{ color:primary?'#FFFDF8':p.ink,fontWeight:'700',fontSize:14,textAlign:primary?'center':'left' }}>{label.startsWith('Open ')?type==='notes'?'Read note':type==='flashcards'?'Study flashcards':type==='tests'?'Take test':'Play game':label}</Text></Pressable>;
  const field = (label:string,value:string,fn:(s:string)=>void,multi=false)=><View><Text style={{ color:p.ink,marginTop:10 }}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={fn} multiline={multi} style={{ color:p.ink,borderColor:p.line,borderWidth:1,borderRadius:12,padding:12,minHeight:multi?120:46,marginTop:5 }} /></View>;
  const panel={ padding:16,borderRadius:22,borderWidth:1,borderColor:p.line,backgroundColor:p.white,marginVertical:8 };
  const materialIcon = type==='notes'?'📒':type==='flashcards'?'🃏':type==='tests'?'📝':'🧩';
  const materialAction = (label:string,fn:()=>void,danger=false) => <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={busy} onPress={fn} style={({pressed})=>({flex:1,minHeight:44,paddingVertical:12,paddingHorizontal:5,borderRadius:12,backgroundColor:pressed?p.softBlue:p.bg,opacity:busy?.5:1})}><Text style={{color:danger?'#B45D49':p.muted,fontSize:11,fontWeight:'700',textAlign:'center'}}>{label.split(' ')[0]}</Text></Pressable>;
  const title=(s:string)=><Text style={{ color:p.navy,fontWeight:'800',fontSize:19,marginVertical:12 }}>{s}</Text>;
  const fresh=()=>({ title:'',materialType:type,content:type==='notes'?{notes:''}:type==='flashcards'?{cards:[blankPair()]}:type==='tests'?{questions:[blankQuestion()]}:{kind:'matching',pairs:[blankPair()]} });
  const uploadNote = async () => {
    const result = await DocumentPicker.getDocumentAsync({ type: ['text/plain','text/markdown','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'], copyToCacheDirectory: true, multiple: false });
    if (result.canceled) return;
    const asset = result.assets[0];
    if (asset.size && asset.size > 8 * 1024 * 1024) throw new Error('Choose a Note file under 8 MB.');
    const body = new FormData();
    await attachUploadFile(body, 'file', asset);
    const imported = await api('/api/cappy/circles/'+room.id+'/notes/import',{ method:'POST',body });
    setAdding(false); setSource(''); setOpened(null); setEditor({ ...fresh(), title: imported.title, content: { notes: imported.notes } });
    setNotice('Review your uploaded Note, then save it to this Circle.');
  };
  const edit=(m:any,replace=false)=>{ setOpened(null); setEditor(replace?{...fresh(),id:m.id,replace:true}:{...JSON.parse(JSON.stringify(m)),replace:false}); };
  const updateContent=(value:any)=>setEditor({...editor,content:{...editor.content,...value}});
  const open=(m:any)=>{ setAdding(false); setSource(''); setActions(null); setOpened(JSON.parse(JSON.stringify(m))); setEditor(null); setCard(0); setFlipped(false); setAnswers({}); setScore(null); setMatch(null); setMatched([]); setRight(shuffle(m.content.pairs?.map((_:any,i:number)=>i) || [])); setScrambled((m.content.pairs || []).map((x:any)=>{ const letters=shuffle([...x.back]); let result=letters.join(''); if(result===x.back && letters.length>1) result=result.slice(1)+result[0]; return result; })); setNotice(''); };
  const save=async()=>{ await api(editor.id?base+'/'+editor.id:base,{method:editor.id?'PUT':'POST',body:JSON.stringify(editor)}); setEditor(null); await refresh(); };
  const shared=room.materials.filter((m:any)=>m.materialType===type);
  const pairsEditor=()=>{ const key=type==='flashcards'?'cards':'pairs', pairs=editor.content[key]; return <>{pairs.map((pair:any,i:number)=><View key={i} style={panel}>{field('Question / front '+(i+1),pair.front,v=>updateContent({[key]:pairs.map((x:any,j:number)=>j===i?{...x,front:v}:x)}))}{field('Answer / back '+(i+1),pair.back,v=>updateContent({[key]:pairs.map((x:any,j:number)=>j===i?{...x,back:v}:x)}))}{button('Remove pair '+(i+1),()=>updateContent({[key]:pairs.filter((_:any,j:number)=>i!==j)}),pairs.length===1)}</View>)}{button('+ Add question / answer',()=>updateContent({[key]:[...pairs,blankPair()]}))}</>; };
  const finish=async()=>{ const qs=opened.materialType==='tests'?opened.content.questions:opened.content.pairs; const n=qs.reduce((sum:number,q:any,i:number)=>sum+(String(answers[i] || '').trim().toLowerCase()===(q.answer || q.back).trim().toLowerCase()?1:0),0); if(opened.content.kind==='group-challenge') { const result=await api(base+'/'+opened.id+'/results',{method:'POST',body:JSON.stringify({answers:qs.map((_:any,i:number)=>answers[i] || '')})}); setScore(result.score); await refresh(); } else setScore(n); };
  const libraryMatches=library.filter((n:any)=>n.name.toLowerCase().includes(librarySearch.toLowerCase()));
  const shareLibrary=(n:any)=>run(async()=>{await api(base,{method:'POST',body:JSON.stringify(circleLibraryCopy(n))});setAdding(false);setSource('');setNotice(singular+' shared with this Circle.');await refresh();});
  const libraryChooser=()=> <View style={panel}>{title('Choose '+singular.toLowerCase()+' from your Library')}<Text style={{color:p.muted,lineHeight:21}}>Select one to share with this Circle. Your original stays in your Library.</Text>{field('Search my Library',librarySearch,v=>{setLibrarySearch(v);setLibraryLimit(8);})}{libraryMatches.slice(0,libraryLimit).map((n:any)=><View key={n.id} style={{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderColor:p.line}}><Text numberOfLines={2} style={{flex:1,color:p.ink,fontSize:14,lineHeight:21}}>{n.name}</Text><Pressable accessibilityRole="button" accessibilityLabel={'Share '+n.name} disabled={busy} onPress={()=>shareLibrary(n)} style={{padding:12,minHeight:44,borderRadius:12,backgroundColor:p.blue}}><Text style={{color:'#FFFDF8',fontWeight:'700'}}>Share</Text></Pressable></View>)}{!libraryMatches.length && <Text style={{color:p.muted,marginVertical:16}}>{library.length?'No matches. Try another name.':'No saved '+type+' yet.'}</Text>}{libraryMatches.length>libraryLimit && button('Show more',()=>setLibraryLimit(libraryLimit+8))}{button('Cancel sharing',()=>{setSource('');setAdding(false);setError('');})}</View>;
  return <View>{!opened && title(editor?(editor.id?'Edit ':'Create ')+singular:'Shared '+type)}{!opened && !editor && <Text style={{color:p.muted,lineHeight:22}}>{type==='notes'?'Read and share notes with your study buddies.':type==='flashcards'?'Practice together with shared flashcard sets.':type==='tests'?'Check your understanding with Circle practice tests.':'Learn together through short study games.'}</Text>}{!!error && <Text accessibilityLiveRegion="polite" style={{ color:'#C44545',marginTop:8 }}>{error}</Text>}{!!notice && <Text accessibilityLiveRegion="polite" style={{ color:p.ink }}>{notice}</Text>}
    {confirmation && <View style={panel}>{title(confirmation.label)}<Text style={{ color:p.muted }}>Personal Library originals stay intact.</Text>{button('Confirm '+confirmation.kind,()=>run(async()=>{ await confirmation.action(); setConfirmation(null); }))}{button('Cancel',()=>setConfirmation(null))}</View>}
    {!editor && !opened && source!=='library' && <View style={{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:12}}><View style={{flexGrow:1,flexBasis:200}}>{button(type==='notes'?'+ Add notes':'+ Add '+(type==='flashcards'?'Deck':type==='tests'?'Test':'Game'),()=>{setError('');setNotice('');if(type==='notes')setAdding(!adding);else setEditor(fresh());},false,true)}</View><View style={{flexGrow:1,flexBasis:200}}>{button('Choose from my Library',()=>{setError('');setSource('library');setLibrarySearch('');setLibraryLimit(8);})}</View></View>}
    {adding && source!=='library' && !editor && !opened && <View style={panel}>{title('Add a Note')}{button('Write a Note',()=>{setAdding(false);setEditor(fresh());})}{button('Upload Note file',()=>run(uploadNote))}<Text style={{color:p.muted,fontSize:12,marginTop:8}}>TXT, Markdown, PDF or DOCX. Up to 8 MB.</Text>{button('Cancel adding notes',()=>setAdding(false))}</View>}
    {source==='library' && !editor && !opened && libraryChooser()}
    {!editor && !opened && source!=='library' && shared.map((m:any)=><View key={m.id} style={panel}><View style={{flexDirection:'row',gap:12,alignItems:'center'}}><View style={{width:48,height:52,borderRadius:12,backgroundColor:p.softBlue,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:26}}>{materialIcon}</Text></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={2} style={{color:p.navy,fontSize:17,fontWeight:'800',lineHeight:23}}>{m.title}</Text><Text style={{color:p.muted,fontSize:11}}>{type==='flashcards'?m.content.cards.length+' cards':type==='tests'?m.content.questions.length+' questions':type==='games'?gameLabels[m.content.kind]?.name || 'Study game':'A shared page for your ideas'}</Text></View></View><View style={{flexDirection:'row',gap:8,alignItems:'center'}}><View style={{flex:1}}>{button('Open '+m.title,()=>type==='games'?run(async()=>{await api(base+'/'+m.id+'/start',{method:'POST',body:'{}'});open(m);await refresh();}):open(m),false,true)}</View><Pressable accessibilityRole="button" accessibilityLabel={'Options for '+m.title} onPress={()=>setActions(actions===m.id?null:m.id)} style={{padding:14,minHeight:44,marginTop:8}}><Text style={{color:p.muted,fontWeight:'700'}}>More</Text></Pressable></View>{actions===m.id && <View style={{flexDirection:'row',gap:6,marginTop:10}}>{materialAction('Edit '+m.title,()=>edit(m))}{materialAction('Replace '+m.title,()=>setConfirmation({label:'Replace '+m.title+'?',kind:'Replace',action:async()=>edit(m,true)}))}{materialAction('Delete '+m.title,()=>setConfirmation({label:'Delete '+m.title+' from this Circle?',kind:'Delete',action:async()=>{ await api(base+'/'+m.id,{method:'DELETE'}); if(opened?.id===m.id)setOpened(null); await refresh(); }}),true)}</View>}</View>)}
    {!shared.length && !editor && !opened && !adding && source!=='library' && <Text style={{ color:p.muted,marginTop:12 }}>Nothing shared yet. Add the first {type==='notes'?'note':type==='flashcards'?'deck':type==='tests'?'test':'activity'}.</Text>}
    {editor && <View style={panel}><Text style={{color:p.muted,lineHeight:22}}>{editor.replace?'Replace the Circle copy. Your Library original stays unchanged.':'Give it a name and add your content below.'}</Text>{field('Material name',editor.title,v=>setEditor({...editor,title:v}))}
      {type==='notes' && field('Shared Note',editor.content.notes,v=>updateContent({notes:v}),true)}
      {type==='games' && <>{title('Game type')}<View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{kinds.map(k=><Pressable key={k} accessibilityRole="radio" accessibilityLabel={k} accessibilityState={{checked:editor.content.kind===k}} disabled={busy} onPress={()=>updateContent({kind:k})} style={{flexGrow:1,flexBasis:230,padding:14,borderRadius:16,borderWidth:2,borderColor:editor.content.kind===k?p.blue:p.line,backgroundColor:editor.content.kind===k?p.softBlue:p.white}}><Text style={{color:p.ink,fontWeight:'800',fontSize:14}}>{editor.content.kind===k?'? ':''}{gameLabels[k].name}</Text><Text style={{color:p.muted,lineHeight:20,fontSize:12,marginTop:5}}>{gameLabels[k].hint}</Text></Pressable>)}</View>{room.materials.some((m:any)=>m.materialType==='flashcards' || m.materialType==='tests') && <>{title('Reuse Circle study questions')}{room.materials.filter((m:any)=>m.materialType==='flashcards' || m.materialType==='tests').map((m:any)=><React.Fragment key={m.id}>{button('Use '+m.title,()=>updateContent({pairs:m.materialType==='flashcards'?JSON.parse(JSON.stringify(m.content.cards)):m.content.questions.map((q:any)=>({front:q.question,back:q.answer}))}))}</React.Fragment>)}</>}</>}
      {(type==='flashcards' || type==='games') && pairsEditor()}
      {type==='tests' && <>{editor.content.questions.map((q:any,i:number)=>{ const qs=editor.content.questions, change=(v:any)=>updateContent({questions:qs.map((x:any,j:number)=>i===j?{...x,...v}:x)}); return <View key={i} style={panel}>{title('Question '+(i+1))}{['multiple-choice','true-false','identification'].map(t=><React.Fragment key={t}>{button((q.type===t?'✓ ':'')+t,()=>change({type:t,answer:'',options:t==='true-false'?['True','False']:t==='multiple-choice'?['','']:[]}))}</React.Fragment>)}{field('Question '+(i+1),q.question,v=>change({question:v}))}{q.type==='multiple-choice' && <>{q.options.map((o:string,j:number)=><React.Fragment key={j}>{field('Option '+(j+1)+' for question '+(i+1),o,v=>change({options:q.options.map((x:string,n:number)=>n===j?v:x)}))}</React.Fragment>)}{button('Add option to question '+(i+1),()=>change({options:[...q.options,'']}))}</>}{q.type==='true-false'?<>{button('Correct: True',()=>change({answer:'True'}))}{button('Correct: False',()=>change({answer:'False'}))}<Text style={{color:p.ink}}>Correct answer: {q.answer || 'Choose above'}</Text></>:field('Correct answer '+(i+1),q.answer,v=>change({answer:v}))}{button('Remove question '+(i+1),()=>updateContent({questions:qs.filter((_:any,j:number)=>i!==j)}),qs.length===1)}</View>; })}{button('+ Add question',()=>updateContent({questions:[...editor.content.questions,blankQuestion()]}))}</>}
      {button('Save shared '+type,()=>run(save),!editor.title.trim(),true)}{button('Cancel editing',()=>setEditor(null))}
    </View>}
    {opened && !editor && <View style={panel}>{title(opened.title)}{button('Back to shared '+type,()=>setOpened(null))}<View style={{flexDirection:'row',gap:6}}>{materialAction('Edit '+opened.title,()=>edit(opened))}{materialAction('Delete '+opened.title,()=>setConfirmation({label:'Delete '+opened.title+' from this Circle?',kind:'Delete',action:async()=>{await api(base+'/'+opened.id,{method:'DELETE'});setOpened(null);await refresh();}}),true)}</View>
      {type==='notes' && <CircleNoteReader text={opened.content.notes} p={p}/>}
      {type==='flashcards' && <>{title('Card '+(card+1)+' / '+opened.content.cards.length)}<Pressable accessibilityRole="button" accessibilityLabel="Flip card" onPress={()=>setFlipped(!flipped)} style={{ minHeight:180,padding:25,backgroundColor:p.softBlue,borderRadius:22,justifyContent:'center' }}><Text style={{ color:p.ink,textAlign:'center',fontSize:20 }}>{opened.content.cards[card][flipped?'back':'front']}</Text><Text style={{ color:p.muted,textAlign:'center',marginTop:20 }}>Tap to flip · {flipped?'Answer':'Question'}</Text></Pressable>{button('Previous card',()=>{setCard(card-1);setFlipped(false);},card===0)}{button('Next card',()=>{setCard(card+1);setFlipped(false);},card===opened.content.cards.length-1)}</>}
      {type==='games' && opened.content.kind==='matching' && <>{title('Match each question to its answer')}<Text style={{ color:p.muted }}>Choose a question, then its matching answer.</Text><View style={{ flexDirection:'row',gap:12 }}><View style={{ flex:1 }}>{opened.content.pairs.map((pair:any,i:number)=><React.Fragment key={i}>{button((match===i?'✓ ':'')+pair.front,()=>setMatch(i),matched.includes(i))}</React.Fragment>)}</View><View style={{ flex:1 }}>{right.map(i=><React.Fragment key={i}>{button(opened.content.pairs[i].back,()=>{if(match===i){setMatched([...matched,i]);setMatch(null);setNotice('Matched!');}else setNotice('Try another answer.');},matched.includes(i) || match===null)}</React.Fragment>)}</View></View>{matched.length===opened.content.pairs.length && title('Great job! '+matched.length+' / '+matched.length)}</>}
      {(type==='tests' || (type==='games' && opened.content.kind!=='matching')) && <>{(type==='tests'?opened.content.questions:opened.content.pairs).map((q:any,i:number)=><View key={i} style={panel}>{title((i+1)+'. '+(opened.content.kind==='word-scramble'?scrambled[i]:q.question || q.front))}{opened.content.kind==='word-scramble' && <Text style={{ color:p.muted }}>Hint: {q.front}</Text>}{q.options?.length ? q.options.map((o:string)=><React.Fragment key={o}>{button((answers[i]===o?'✓ ':'')+o,()=>setAnswers({...answers,[i]:o}),score!==null)}</React.Fragment>):field('Your answer '+(i+1),answers[i] || '',v=>{if(score===null)setAnswers({...answers,[i]:v});})}{score!==null && <Text style={{ color:p.ink }}>Correct answer: {q.answer || q.back}</Text>}</View>)}{score===null?button('Finish and show score',()=>run(finish)): <>{title(score+' / '+(type==='tests'?opened.content.questions.length:opened.content.pairs.length))}<Text style={{ color:p.ink }}>{score>0?'Great job!':'Keep practicing. You can try again.'}</Text>{button('Try again',()=>open(opened))}</>}</>}
      {type==='games' && opened.content.kind==='group-challenge' && <>{title('Circle Challenge scores')}{(room.materials.find((m:any)=>m.id===opened.id)?.results || []).sort((a:any,b:any)=>b.score-a.score).map((r:any)=><Text key={r.userId} style={{ color:p.ink,paddingVertical:6 }}>{room.participants.find((m:any)=>m.userId===r.userId)?.name || 'Former member'} · {r.score} / {r.total}</Text>)}</>}
    </View>}
  </View>;
}
