import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, ScrollView, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { cappyPalette, darkPalette } from './cappy';
import { CircleMaterials } from './circle-materials';
import { CappyMascot } from './cappy-mascot';
import { CircleRoomScene } from './circle-room-scene';
import { CircleForm } from './circle-form';
import { CircleCapybaraEditor } from './circle-capybara';
import AsyncStorage from '@react-native-async-storage/async-storage';
const ROOT = '/api/cappy/circles';
const emptyForm = { circleName: '', subject: '', description: '', privacy: 'public' };
export function StudyCircles({ api, dark, noteId }: { api: any; dark: boolean; noteId?: string }) {
  const p = dark ? darkPalette : cappyPalette, { width } = useWindowDimensions();
  const [home,setHome] = useState<any>({ sessions: [], discover: [], invitations: [] });
  const [search,setSearch] = useState(''), [room,setRoom] = useState<any>(null), [form,setForm] = useState<any>(null);
  const [tab,setTab] = useState('room'), [message,setMessage] = useState(''), [error,setError] = useState(''), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true);
  const [memberSearch,setMemberSearch] = useState(''), [email,setEmail] = useState(''), [confirm,setConfirm] = useState<{ label: string; action: () => Promise<void> } | null>(null);
  const [customizing,setCustomizing] = useState(false);
  const [localJackets,setLocalJackets] = useState<Record<string,any>>({}), [jacketNotice,setJacketNotice]=useState('');
  const jacketKey=(id:string,user:string)=>'circle-jacket:'+user+':'+id;
  const active = useRef(''), generation = useRef(0);
  const loadHome = async () => { const r = await api(ROOT + '?search=' + encodeURIComponent(search)); setHome({ sessions: [], discover: [], invitations: [], ...r }); };
  const refreshRoom = async () => { const id = active.current; if (!id) return; const r = await api(ROOT + '/' + id); if (active.current === id) setRoom(r.session); };
  const run = async (fn: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); try { await fn(); } catch(e:any) { setError(e.message === 'Choose notes you created in your library.' ? 'The account server needs the Circle update before you can create a Circle without Notes.' : e.message || 'Please try again.'); } finally { setBusy(false); } };
  useEffect(() => { let live = true; const load = async () => { try { const r = await api(ROOT + '?search=' + encodeURIComponent(search)); if (live) setHome({ sessions: [], discover: [], invitations: [], ...r }); } catch(e:any) { if (live) setError(e.message); } finally { if (live) setLoading(false); } }; load(); const timer = setInterval(load,12000); return () => { live = false; clearInterval(timer); }; },[search,api]);
  useEffect(() => { if (!room?.id) return; const id = room.id; const timer = setInterval(() => { api(ROOT + '/' + id).then((r:any) => { if (active.current === id) setRoom(r.session); }).catch((e:any) => { if (active.current === id) { setError(e.message); active.current = ''; setRoom(null); } }); },5000); return () => clearInterval(timer); },[room?.id,api]);
  useEffect(() => () => { active.current = ''; generation.current++; },[]);
  const enter = async (id:string) => { const g = ++generation.current; const r = await api(ROOT + '/' + id);const saved=await AsyncStorage.getItem(jacketKey(id,r.session.currentUserId));if(saved){try{const value=JSON.parse(saved);if(['blue','green','pink','orange','yellow','red','black'].includes(value.jacketColor))setLocalJackets(previous=>({...previous,[id]:value}));}catch{}}setJacketNotice(''); if (g === generation.current) { active.current = id; setRoom(r.session); setMessage(''); setTab(noteId ? 'notes' : 'room'); } };
  const leaveView = () => { active.current = ''; generation.current++; setRoom(null); setCustomizing(false); setForm(null); setConfirm(null); setMessage(''); };
  const button = (label:string, action:() => void, disabled = false) => <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={busy || disabled} onPress={action} style={({pressed})=>({ padding:12, minHeight:44, marginTop:8, borderRadius:16, backgroundColor:pressed?p.line:p.softBlue, borderWidth:1, borderColor:p.line, opacity:busy || disabled ? .5 : 1 })}><Text style={{ color:p.ink, fontWeight:'700', textAlign:'center' }}>{label}</Text></Pressable>;
  const heading = (s:string) => <Text style={{ color:p.navy,fontWeight:'800',fontSize:20,marginVertical:14 }}>{s}</Text>;
  const field = (label:string,value:string,onChange:(s:string)=>void,multiline=false) => <View><Text style={{ color:p.ink,marginTop:10 }}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} placeholder={label.startsWith('Search') ? 'Search by name…' : undefined} placeholderTextColor={p.muted} style={{ color:p.ink,borderColor:p.line,borderWidth:1,borderRadius:14,padding:12,minHeight:multiline ? 90 : 46,marginTop:6 }} /></View>;
  const panel = { padding:18,borderRadius:24,borderWidth:1,borderColor:p.line,backgroundColor:p.white,marginVertical:8 };
  const card = (c:any,own:boolean) => <View key={c.id} style={{...panel,width:width>=760?'48.5%':'100%',borderTopWidth:4,borderTopColor:own?p.blue:dark?'#7B8660':'#A7B58A'}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8}}><View style={{width:42,height:42,borderRadius:15,backgroundColor:p.softBlue,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:23}}>{own?'📚':'🌱'}</Text></View><Text style={{color:p.muted,fontSize:10,padding:7,borderRadius:10,backgroundColor:p.bg}}>{c.privacy==='private'?'Invite only':'Open to requests'}</Text></View>{heading(c.circleName)}<Text style={{ color:p.muted,fontSize:12 }}>{c.subject || 'All subjects'} · {c.memberCount} members</Text><Text numberOfLines={3} style={{ color:p.ink,marginTop:12,lineHeight:21,minHeight:42 }}>{c.description || 'A little space to learn together.'}</Text><Text style={{ color:p.muted,marginTop:12,fontSize:11 }}>Created by {c.creatorName}</Text>{own ? button('Enter ' + c.circleName,()=>run(()=>enter(c.id))) : button(c.status === 'pending' ? 'Request Sent' : 'Request to Join',()=>run(async()=>{ await api(ROOT+'/'+c.id+'/requests',{method:'POST',body:'{}'}); await loadHome(); }),c.status === 'pending')}</View>;
  const prioritized = room ? room.participants.map((m:any)=>m.userId===room.currentUserId && localJackets[room.id]?{...m,capybara:localJackets[room.id]}:m).sort((a:any,b:any) => {
    const priority = (m:any) => m.userId === room.currentUserId ? 0 : m.userId === room.creatorId ? 1 : m.online ? 2 : 3;
    return priority(a)-priority(b) || (Date.parse(b.lastSeenAt || b.joinedAt) || 0)-(Date.parse(a.lastSeenAt || a.joinedAt) || 0);
  }) : [];
  return <View style={{ paddingBottom:24,maxWidth:1040,width:'100%',alignSelf:'center' }}><View style={{ padding:18,borderRadius:28,backgroundColor:p.softBlue,borderWidth:1,borderColor:p.line,marginBottom:14 }}><Text style={{ color:p.blue,fontSize:9,fontWeight:'800',letterSpacing:1 }}>STUDYante · A LITTLE MORE POSSIBLE</Text><View style={{ flexDirection:'row',alignItems:'center',gap:8 }}><View style={{ flex:1,minWidth:0 }}><Text style={{color:p.navy,fontSize:room?25:30,fontWeight:'800',letterSpacing:-.6,marginVertical:10}}>{room ? room.circleName : 'Study Circle'}</Text><Text style={{ color:p.ink,lineHeight:21,fontSize:13 }}>Find your circle. Learn together.</Text></View><CappyMascot size={width<380?70:94} /></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:16}}>{(room?[room.privacy==='private'?'🔒 Invite only':'🌿 Public Circle','📚 '+room.materials.length+' shared materials']:['🌿 Find your people','📖 Learn at your pace']).map(label=><View key={label} style={{borderRadius:20,paddingVertical:7,paddingHorizontal:10,backgroundColor:p.white}}><Text style={{color:p.muted,fontSize:10,fontWeight:'600'}}>{label}</Text></View>)}</View></View>
    {!!error && <Text accessibilityLiveRegion="polite" style={{ color:'#C44545',marginVertical:12 }}>{error}</Text>}{loading && <ActivityIndicator color={p.blue} />}
    {confirm && <View style={panel}><Text style={{ color:p.ink }}>{confirm.label}</Text>{button('Confirm',()=>run(async()=>{ await confirm.action(); setConfirm(null); }))}{button('Cancel',()=>setConfirm(null))}</View>}
    {form && <View><Pressable accessibilityRole="button" accessibilityLabel={form.edit?'Back to Circle':'Back to Study Circle'} disabled={busy} onPress={()=>{setForm(null);setError('');}} style={{paddingVertical:14,minHeight:44,marginBottom:10}}><Text style={{color:p.blue,fontWeight:'700'}}>← {form.edit?'Back to Circle':'Back to Study Circle'}</Text></Pressable><CircleForm value={form} onChange={setForm} p={p} dark={dark} busy={busy} onCancel={()=>{setForm(null);setError('');}} onSave={()=>run(async()=>{if(form.edit){await api(ROOT+'/'+room.id,{method:'PATCH',body:JSON.stringify(form)});await refreshRoom();}else{const r=await api(ROOT,{method:'POST',body:JSON.stringify(form)});await enter(r.session.id);}setForm(null);await loadHome();})} /></View>}
    {!form && (!room ? <><View style={{flexDirection:width<560?'column':'row',gap:12,alignItems:width<560?'stretch':'center',marginVertical:8}}><View style={{flex:width<560?undefined:1,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:p.white,borderWidth:1,borderColor:p.line,borderRadius:16,paddingHorizontal:14}}><Text style={{color:p.muted,fontSize:19}}>⌕</Text><TextInput accessibilityLabel="Search circle name..." placeholder="Search circle name..." placeholderTextColor={p.muted} value={search} onChangeText={setSearch} style={{flex:1,minWidth:0,minHeight:50,color:p.ink,paddingVertical:12}} /></View><Pressable accessibilityRole="button" accessibilityLabel="+ Create Circle" onPress={()=>{setError('');setForm({...emptyForm});}} style={{backgroundColor:p.blue,borderRadius:16,paddingVertical:15,paddingHorizontal:22,minHeight:50}}><Text style={{color:dark?'#352920':'#FFFDF8',fontWeight:'800',textAlign:'center'}}>+ Create Circle</Text></Pressable></View>{heading('YOUR CIRCLES')}{!home.sessions.length && <View style={{...panel,alignItems:'center',padding:24,borderStyle:'dashed'}}><Text style={{fontSize:32,marginBottom:10}}>🌱</Text><Text style={{color:p.navy,fontWeight:'700',marginBottom:8}}>Your next study buddy starts here.</Text><Text style={{color:p.muted,textAlign:'center',lineHeight:20,fontSize:12}}>Your accepted circles will appear here.</Text></View>}{<View style={{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'}}>{home.sessions.map((c:any)=>card(c,true))}</View>}{home.invitations.length > 0 && heading('INVITATIONS')}{home.invitations.map((c:any)=><View key={c.id} style={panel}>{heading(c.circleName)}<Text style={{ color:p.ink }}>{c.creatorName} invited you.</Text>{['accepted','declined'].map(status=>button(status==='accepted'?'Accept invitation':'Decline invitation',()=>run(async()=>{ await api(ROOT+'/'+c.id+'/respond',{method:'POST',body:JSON.stringify({status})}); await loadHome(); })))}</View>)}{heading('DISCOVER CIRCLES')}{!home.discover.length && <Text style={{ color:p.muted }}>No searchable circles match yet.</Text>}{<View style={{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'}}>{home.discover.map((c:any)=>card(c,false))}</View>}</> : <>
      {button('Back to Study Circle',leaveView)}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap:8,paddingVertical:4 }} style={{ marginVertical:12 }}>{['room','notes','flashcards','tests','games','members','activity',...(room.mine ? ['requests','management'] : [])].map(t=>{const label=t==='requests'?'Join Requests ('+room.requests.length+')':t==='notes'?'Notes':t.charAt(0).toUpperCase()+t.slice(1);return <Pressable key={t} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{selected:tab===t}} onPress={()=>setTab(t)} style={{paddingVertical:12,paddingHorizontal:16,minHeight:44,borderRadius:24,backgroundColor:tab===t?p.blue:p.white,borderWidth:1,borderColor:p.line}}><Text style={{color:tab===t?(dark?'#352920':'#FFFDF8'):p.muted,fontSize:12,fontWeight:'700'}}>{label}</Text></Pressable>;})}</ScrollView>
      {tab==='room' && <View>
        <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:14}}><View style={{flex:1}}><Text style={{color:p.navy,fontSize:20,fontWeight:'800'}}>Study room</Text><Text style={{color:p.muted,fontSize:12,marginTop:4}}>Settle in and learn together.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Customize my capybara" onPress={()=>{setError('');setCustomizing(!customizing);}} style={{padding:12,minHeight:44,borderRadius:16,borderWidth:1,borderColor:p.line,backgroundColor:p.white}}><Text style={{color:p.blue,fontWeight:'700'}}>My capybara</Text></Pressable></View>
        {customizing && <CircleCapybaraEditor value={localJackets[room.id] || room.participants.find((m:any)=>m.userId===room.currentUserId)?.capybara} p={p} busy={busy} error={error} onCancel={()=>setCustomizing(false)} onSave={(value:any)=>run(async()=>{
          let synced=true;
          try {await api(ROOT+'/'+room.id+'/capybara',{method:'PATCH',body:JSON.stringify(value)});const verified=await api(ROOT+'/'+room.id);if(verified.session?.participants?.find((m:any)=>m.userId===room.currentUserId)?.capybara?.jacketColor!==value.jacketColor)throw new Error('Circle jacket update missing');if(active.current===room.id)setRoom(verified.session);}
          catch(e:any){if(!/Circle jacket update|Circle jacket update missing/.test(e.message))throw e;synced=false;}
          await AsyncStorage.setItem(jacketKey(room.id,room.currentUserId),JSON.stringify(value));setLocalJackets(previous=>({...previous,[room.id]:value}));setJacketNotice(synced?'Jacket saved for this Circle.':'Jacket saved on this device. Other members will see the new color after the Circle server update.');setCustomizing(false);
        })}/>}
        {!!jacketNotice && <Text accessibilityLiveRegion="polite" style={{color:p.muted,lineHeight:21,marginBottom:12}}>{jacketNotice}</Text>}

        <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,marginBottom:12}}><Text numberOfLines={1} style={{color:p.muted,flex:1,fontSize:12}}>{room.subject || 'Our cozy study room'}</Text><Text style={{color:p.blue,fontSize:11,fontWeight:'700'}}>{room.memberCount} study buddies</Text></View>
        <CircleRoomScene room={room} members={prioritized} p={p} dark={dark} onOpen={setTab} onChat={()=>setTab('chat')} onMembers={()=>setTab('members')} />
        <View style={{...panel,padding:12}}><Text style={{color:p.muted,fontSize:11,marginBottom:8}}>Messages appear above capybaras for 10 seconds. Full chat keeps every message.</Text><View style={{flexDirection:'row',alignItems:'center',gap:8}}><TextInput accessibilityLabel="Type a message..." placeholder="Type a message..." placeholderTextColor={p.muted} value={message} onChangeText={setMessage} maxLength={2000} style={{flex:1,minWidth:0,minHeight:46,padding:12,borderRadius:16,backgroundColor:p.bg,color:p.ink,borderWidth:1,borderColor:p.line}} /><Pressable accessibilityRole="button" accessibilityLabel="Send" disabled={busy || !message.trim()} onPress={()=>run(async()=>{await api(ROOT+'/'+room.id+'/messages',{method:'POST',body:JSON.stringify({message})});setMessage('');await refreshRoom();})} style={{padding:13,borderRadius:16,backgroundColor:p.blue,opacity:busy || !message.trim() ? 0.45 : 1}}><Text style={{color:dark?'#352920':'#FFFDF8',fontWeight:'800'}}>Send ↗</Text></Pressable></View>{button('Full Circle chat history',()=>setTab('chat'))}</View>
      </View>}
      {tab==='chat' && <View style={panel}>{heading('Circle chat history')}<FlatList style={{ maxHeight:420 }} data={room.messages} keyExtractor={(m:any)=>m.id} renderItem={({item:m}:any)=><View style={{ padding:12,marginVertical:4,borderRadius:16,backgroundColor:p.softBlue }}><Text style={{ color:p.blue,fontWeight:'700' }}>{m.name} · {new Date(m.createdAt).toLocaleTimeString()}</Text><Text selectable style={{ color:p.ink }}>{m.message}</Text></View>} />{field('Type a message...',message,setMessage)}{button('Send',()=>run(async()=>{ await api(ROOT+'/'+room.id+'/messages',{method:'POST',body:JSON.stringify({message})}); setMessage(''); await refreshRoom(); }),!message.trim())}{button('Back to room',()=>setTab('room'))}</View>}
      {tab==='members' && <View style={panel}>{heading('Circle Members')}{field('Search members',memberSearch,setMemberSearch)}<FlatList style={{ maxHeight:430 }} data={prioritized.filter((m:any)=>m.name.toLowerCase().includes(memberSearch.toLowerCase()))} keyExtractor={(m:any)=>m.userId} renderItem={({item:m}:any)=><View style={{ padding:10,borderBottomWidth:1,borderColor:p.line }}><Text style={{ color:p.ink }}>{m.name} · {m.role === 'creator' ? '👑 Creator' : 'Member'} · {m.online?'Online':'Offline'}</Text>{room.mine && m.role!=='creator' && button('Remove '+m.name,()=>setConfirm({label:'Remove '+m.name+' from this Circle?',action:async()=>{ await api(ROOT+'/'+room.id+'/members/'+encodeURIComponent(m.userId),{method:'DELETE'}); await refreshRoom(); }}))}</View>} /></View>}
      {tab==='requests' && room.mine && <View style={panel}>{heading('Join Requests')}{!room.requests.length && <Text style={{ color:p.muted }}>No pending requests.</Text>}{room.requests.map((r:any)=><View key={r.id}><Text style={{ color:p.ink }}>{r.name}</Text>{['accepted','declined'].map(status=>button((status==='accepted'?'Accept ':'Decline ')+r.name,()=>run(async()=>{ await api(ROOT+'/'+room.id+'/requests/'+r.id,{method:'POST',body:JSON.stringify({status})}); await refreshRoom(); })))}</View>)}</View>}
      {tab==='management' && <View style={panel}>{room.mine && <>{button('Edit Circle details',()=>setForm({...room,edit:true}))}{field('Invite an account by email',email,setEmail)}{button('Send Circle invitation',()=>run(async()=>{ await api(ROOT+'/'+room.id+'/invitations',{method:'POST',body:JSON.stringify({email})}); setEmail(''); }),!email.trim())}</>}{button(room.mine?'Delete Circle':'Leave Circle',()=>setConfirm({label:room.mine?'Delete this Circle and its shared content? Personal Library notes are kept.':'Leave this Circle?',action:async()=>{ await api(ROOT+'/'+room.id,{method:'DELETE'}); leaveView(); await loadHome(); }}))}</View>}
      {!room.mine && button('Leave Circle',()=>setConfirm({label:'Leave this Circle?',action:async()=>{ await api(ROOT+'/'+room.id,{method:'DELETE'}); leaveView(); await loadHome(); }}))}
      {tab==='activity' && <View style={panel}>{heading('Shared Activity')}{!room.activity.length && <Text style={{ color:p.muted }}>Shared activity will appear here.</Text>}{[...room.activity].reverse().map((a:any)=><Text key={a.id} style={{ color:p.ink,paddingVertical:9 }}>{a.name} {a.action} · {a.materialType} · {a.title}</Text>)}</View>}
      {['notes','flashcards','tests','games'].includes(tab) && <CircleMaterials key={room.id+tab} api={api} room={room} type={tab} p={p} refresh={refreshRoom} noteId={noteId} onBack={()=>setTab('room')} />}
    </>)}
  </View>;
}
